### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jacmoe** [balintkiss501/raycaster-engine#1]
Hello,

I am wondering, could you perhaps add a license?
Preferably a permissive license, like MIT.
I am implementing an old school raycaster project, and this would be a most excellent starting point.
Thank you in advance :)

**Comment by balintkissdev** [comment]
Hi,

Thanks for notifying it, I'll add MIT after I get back from my job. It was just an old pet project of mine from years ago that I was planning to refactor and add texture mapping to it anyway, but feel free to use it as a reference.

**Comment by jacmoe** [comment]
That sounds great, thank you 👍 
I like that it is sparse and thus ready to be fleshed out. No need to defend your pet project from years ago 😄 It has the right amount of engineering and I like that.
No rush adding the license. MIT sounds good to me. Thanks again!

**Comment by balintkissdev** [comment]
Done!
